
import { NgModule } from "@angular/core";
import {
    SpecialCharactersSingleSpaceDirective, NumbersDirective, AlphabetsSpecialSingleSpaceDirective,
    NumericSpecialSingleSpaceDirective, AlphaNumericSingleSpaceDirective, EmailDirective, DomainDirective,
    HtmlTagDirective, MultiEmailDirective, CharactersSingleSpaceDirective, AllowAllSingleSpaceDirective,
    NumbersCommaSingleSpaceDirective, SelectedSpecailCharactersDirective, CampCalCharactersDirective,
    AlphaNumericNoSpaceDirective, AllowAllNoSpaceDirective, emailCharecters, AlphaNumbersDirective,
    AlphaNumbersnocommaDirective, CharactersWithOutSpaceDirective, AllowArabicSpecialDirective,
    AllowEngilshOnlyDirective, MobileNumberCharecters, ColumnNameCharecters, NumberDirective, NumberCustomDirective,
    AllowAllSpaceDirective, MobileNumberDirective,
    ServiceEnglishDirective, ServiceArbicDirective, ServiceEnglishDirective1, ServiceArbicDirective1, AlphabetsSingleSpaceDirective, AlphaNumericSpecialSingleSpaceDirective, NumbersCommaNoSpaceDirective, MultipleEmailCharecters,  ActionClickDirective
} from "./commonDirective";

@NgModule({
    exports: [
        AlphaNumbersDirective,
        NumbersDirective,
        MultipleEmailCharecters,
        AlphaNumbersnocommaDirective,
        CharactersSingleSpaceDirective,
        AlphabetsSpecialSingleSpaceDirective,
        NumericSpecialSingleSpaceDirective,
        SpecialCharactersSingleSpaceDirective,
        AlphaNumericSingleSpaceDirective,
        NumbersCommaSingleSpaceDirective,
        EmailDirective,
        DomainDirective,
        HtmlTagDirective,
        MultiEmailDirective,
        AllowAllSingleSpaceDirective,
        SelectedSpecailCharactersDirective,
        CampCalCharactersDirective,
        AlphaNumericNoSpaceDirective,
        AllowAllNoSpaceDirective,
        emailCharecters,
        CharactersWithOutSpaceDirective,
        AllowArabicSpecialDirective,
        AllowEngilshOnlyDirective,
        MobileNumberCharecters,
        ColumnNameCharecters,
        NumberDirective,
        NumberCustomDirective,
        AllowAllSpaceDirective,
        MobileNumberDirective,
        ServiceEnglishDirective,
        ServiceArbicDirective,
        AlphabetsSingleSpaceDirective,
        ServiceEnglishDirective1,
        ServiceArbicDirective1,
        AlphaNumericSpecialSingleSpaceDirective,
        NumbersCommaNoSpaceDirective,
        ActionClickDirective
    ],
    declarations: [
        AlphaNumbersDirective,
        NumberDirective,
        NumbersDirective,
        MultipleEmailCharecters,
        AlphaNumbersnocommaDirective,
        CharactersSingleSpaceDirective,
        AllowAllSingleSpaceDirective,
        AlphabetsSpecialSingleSpaceDirective,
        NumbersCommaSingleSpaceDirective,
        NumericSpecialSingleSpaceDirective,
        SpecialCharactersSingleSpaceDirective,
        AlphaNumericSingleSpaceDirective,
        SelectedSpecailCharactersDirective,
        EmailDirective,
        DomainDirective,
        HtmlTagDirective,
        MultiEmailDirective,
        CampCalCharactersDirective,
        AlphaNumericNoSpaceDirective,
        AllowAllNoSpaceDirective,
        emailCharecters,
        CharactersWithOutSpaceDirective,
        AllowArabicSpecialDirective,
        AllowEngilshOnlyDirective,
        MobileNumberCharecters,
        ColumnNameCharecters,
        NumberCustomDirective,
        AllowAllSpaceDirective,
        MobileNumberDirective,
        ServiceEnglishDirective,
        ServiceArbicDirective,
        ServiceEnglishDirective1,
        ServiceArbicDirective1,
        AlphabetsSingleSpaceDirective,
        AlphaNumericSpecialSingleSpaceDirective,
        NumbersCommaNoSpaceDirective,
        ActionClickDirective
    ]
})
export class sharedDirectiveModule {

}